export enum Role {
  PRESIDENT = 'president',
  VICE_PRESIDENT = 'vice_president',
  SIG_PRESIDENT = 'sig_president',
  TREASURER = 'treasurer',
  JUNIOR_TREASURER = 'junior_treasurer',
  SECRETARY = 'secretary',
  HACKATHON_SECRETARY = 'hackathon_secretary',
  TECHNICAL_SECRETARY = 'technical_secretary',
  SOCIAL_SECRETARY = 'social_secretary',
  SOCIAL_MEDIA_OFFICER = 'social_media_officer',
  GRAPHIC_DESIGNER = 'graphic_designer',
  FIRST_YEAR_REP = 'first_year_rep',
  SECOND_YEAR_REP = 'second_year_rep',
  THIRD_YEAR_REP = 'third_year_rep',
  FOURTH_YEAR_REP = 'fourth_year_rep',
  OLD_PERSON_REP = 'old_person_rep',
  EDI_REP = 'edi_rep',
  IMAGE_AND_PR = 'image_and_pr',
  COMMUNICATION = 'communication',
  EU_LUG = 'eu_lug',
}
